== Reactive Streams over Aeron

For more information regarding Aeron go to https://github.com/real-logic/Aeron[Aeron Project Home]

Support of http://www.reactive-streams.org/[Reactive Streams] over Aeron transport introduced in module reactor-aeron.

.Core reactor-aeron classes and their purpose
[cols="m,d", options="header"]
|============================
| Class          | Purpose
| Context        | Provides configuration parameters for AeronSubscriber, AeronPublisher and AeronProcessor
| AeronSubscriber| Plays a role of a server. Passes signals to clients over Aeron.
| AeronPublisher | Plays a role of a client. Receives signals from the server.
| AeronProcessor | Plays both roles of a server and a client.
|============================

=== Quick start

.Starting a server on box serverbox in unicast mode on UDP port 12000:
[source,java]
----
AeronSubscriber subscriber = AeronSubscriber.create(new Context()
    .senderChannel("udp://serverbox:12000"));
----

.Starting a client to be run on box clientbox on UDP port 12001 and connecting to the server on serverbox above:
[source,java]
----
AeronPublisher publisher = AeronPublisher.create(new Context()
    .senderChannel("udp://serverbox:12000")
    .receiverChannel("udp://clientbox:12001"));
----

=== Embedded Aeron Media driver

By default AeronSubscriber, AeronPublisher and AeronProcessor launch embedded Aeron Media Driver if it wasn't launched
previously. Only a single instance of the embedded `MediaDriver` is normally supported per JVM.
Also a single `Aeron` instance is supported when the embedded media driver is used.

If you need to use your own Aeron instance then it needs to be set into `Context.aeron` field.

You can adjust embedded media driver configuration `MediaDriver.Context` via
`EmbeddedMediaDriverManager.getInstance().getDriverContext()`
before the driver is started.

The embedded Media driver shutdown specifics and clean up activity can be set up via fields of
`EmbeddedMediaDriverManager` instance.

=== AeronSubscriber as server

AeronSubscriber plays a role of a server which passes signals from an upstream publisher to receivers via Aeron.

The subscriber is configured via fields of `Context' which have default values and normally there is no need
to adjust them.

.Most important fields of `Context` for `AeronSubscriber`
[cols="m,d", options="header"]
|======================================================
| Field                   | Description
| errorConsumer           | Consumer of errors encountered
| publicationRetryMillis  | Number of milliseconds to wait before giving up publishing of a message into Aeron. +
When publication fails the corresponding exception is reported into `errorConsumer`.
| heartbeatIntervalMillis | Interval in milliseconds for sending heartbeats from a signal receiver to a signal sender.
| multicastUpstreamRequest| Number of signals requested from an upstream publisher in a single call to its subscription
by multicast sender.
| senderChannel           | Aeron channel on which to listen for inbound requests from clients. +
|======================================================

`senderChannel` has the following format: `udp://<Network Interface IP Address>|<Machine name>:<Port>` +
Where `Network Interface IP Address` is the IP address of a network interface used for communication between the sender and receivers. +
Alternatively `Machine name` which is a machine name on the network could be provided as it's resolved to the corresponding network interface IP.

==== Unicast sending mode

==== Multicast sending mode

=== AeronPublisher as client

=== Handling errors